RegisterServerEvent('timers:add')
AddEventHandler('timers:add', function(Weed, Ammonia, Cyclopentyl, Magnesium, Methylamine, Heroin, Cocaine)
 local source = tonumber(source)
 TriggerEvent("core:getPlayerFromId", source, function(user)
  user.addTimer('Weed', Weed)
  user.addTimer('Ammonia', Ammonia)
  user.addTimer('Cyclopentyl', Cyclopentyl)
  user.addTimer('Magnesium', Magnesium)
  user.addTimer('Methylamine', Methylamine)
  user.addTimer('Heroin', Heroin)
  user.addTimer('Cocaine', Cocaine)
  TriggerClientEvent('timers:character', source, user.getTimers())
 end)
end)

RegisterServerEvent('timers:set')
AddEventHandler('timers:set', function(Weed, Ammonia, Cyclopentyl, Magnesium, Methylamine, Heroin, Cocaine)
 local source = tonumber(source)
 TriggerEvent("core:getPlayerFromId", source, function(user)
  user.setTimer('Weed', Weed)
  user.setTimer('Ammonia', Ammonia)
  user.setTimer('Cyclopentyl', Cyclopentyl)
  user.setTimer('Magnesium', Magnesium)
  user.setTimer('Methylamine', Methylamine)
  user.setTimer('Heroin', Heroin)
  user.setTimer('Cocaine', Cocaine)
  TriggerClientEvent('timers:character', source, user.getTimers())
 end)
end)

RegisterServerEvent('timers:load')
AddEventHandler('timers:load', function(source)
 local source = tonumber(source)
 TriggerEvent("core:getPlayerFromId", source, function(user)
  TriggerClientEvent('timers:character', source, user.getTimers())
 end)
end)

TriggerEvent('core:addGroupCommand', 'timers', 'admin', function(source, args, user)
  TriggerEvent("core:getPlayerFromId", source, function(user)
   TriggerClientEvent('chatMessage', source, "^5Current Timers: ")
   for _,v in pairs(user.getTimers()) do
    if v.value > 0 then
      TriggerClientEvent('chatMessage', source, v.name.." - "..v.value.." second(s) remaining.")
    end
   end
  end)
 end)