RegisterServerEvent('rob:getPlayerInventory')
AddEventHandler('rob:getPlayerInventory', function(target)
 local source = tonumber(source)
 local target = tonumber(target)
 local itemMeta = nil 
 TriggerEvent('core:getPlayerFromId', source, function(user)
  TriggerEvent('core:getPlayerFromId', target, function(targetUser) 
   local inventory = targetUser.getInventory(item,qty, itemMeta)
   TriggerClientEvent('rob:inventory', source, inventory, target)
   TriggerClientEvent("inventory:policeopen", source, inventory,target)
   TriggerClientEvent('NRP-notify:client:SendAlert', target, { type = 'error', text = 'You are being searched!', length = 5000}) 
  
  end)
 end)
end)

RegisterServerEvent('rob:getPlayerCash')
AddEventHandler('rob:getPlayerCash', function(target)
 local source = tonumber(source)
 local target = tonumber(target)
 TriggerEvent('core:getPlayerFromId', source, function(user)
  TriggerEvent('core:getPlayerFromId', target, function(targetUser) 
   local money = targetUser.getMoney()
   local dirtymoney = targetUser.getDirtyMoney()
   TriggerClientEvent('rob:cash', source, money, dirtymoney, target)
   TriggerClientEvent('NRP-notify:client:SendAlert', target, { type = 'error', text = 'You are being searched!', length = 5000}) 
   
  end)
 end)
end)



RegisterServerEvent('rob:takeItem')
AddEventHandler('rob:takeItem', function(item, name, qty, target)
 local source = tonumber(source)
 local target = tonumber(target)
 local itemMeta = nil 
 TriggerEvent('core:getPlayerFromId', source, function(user)
  TriggerEvent('core:getPlayerFromId', target, function(targetUser)
   canGive = targetUser.isAbleToGive(item,qty)
   itemMeta = targetUser.getItemMeta(item)
   if canGive then
    targetUser.removeQuantity(item,qty)
    user.addQuantity(item,qty, itemMeta)
    TriggerClientEvent('rob:inventory', source, targetUser.getInventory(), target)
   end
  end)
 end)
end)

RegisterServerEvent('rob:takeMoney')
AddEventHandler('rob:takeMoney', function(amount, target)
 local source = tonumber(source)
 local target = tonumber(target)
 local cash = tonumber(amount)
 TriggerEvent('core:getPlayerFromId', source, function(user)
  TriggerEvent('core:getPlayerFromId', target, function(targetUser)
   targetUser.removeMoney(cash)
   user.addMoney(cash)
   TriggerClientEvent('NRP-notify:client:SendAlert', tonumber(source), { type = 'inform', text = 'You Took $'..cash.." From Player"})
   TriggerClientEvent('NRP-notify:client:SendAlert', target, { type = 'inform', text ='You Had $'..cash.." Taken From You"})
   local money = targetUser.getMoney()
   local dirtymoney = targetUser.getDirtyMoney()
   TriggerClientEvent('rob:cash', source, money, dirtymoney, target)
  end)
 end)
end)

RegisterServerEvent('rob:takedirtyMoney')
AddEventHandler('rob:takedirtyMoney', function(amount, target)
 local source = tonumber(source)
 local target = tonumber(target)
 local cash = tonumber(amount)
 TriggerEvent('core:getPlayerFromId', source, function(user)
  TriggerEvent('core:getPlayerFromId', target, function(targetUser)
   targetUser.removeDirtyMoney(cash)
   if user.getJob() == 1 or user.getJob() == 32 or user.getJob() == 33 or user.getJob() == 34 or user.getJob() == 35 or user.getJob() == 36 or user.getJob() == 37 or user.getJob() == 90 or user.getJob() == 91 then
    user.removeDirtyMoney(user.getDirtyMoney())
   else
    user.addDirtyMoney(cash)
   end
   TriggerClientEvent('NRP-notify:client:SendAlert', tonumber(source), { type = 'inform', text = 'You Took $'..cash.." From Player"})
   TriggerClientEvent('NRP-notify:client:SendAlert', target, { type = 'inform', text ='You Had $'..cash.." Taken From You"})
   local money = targetUser.getMoney()
   local dirtymoney = targetUser.getDirtyMoney()
   TriggerClientEvent('rob:cash', source, money, dirtymoney, target)
  end)
 end)
end)