vehicles = {
   ["Compacts"] = {
      {name = "Blista", price = 22000, model = "blista"},
      {name = "Blista Compact", price = 25000, model = "blista2"},
      {name = "Go Go Monkey Blista", price = 35000, model = "blista3"},
      {name = "Brioso R/A", price = 27000, model = "brioso"},
      {name = "Dilettante", price = 22000, model = "Dilettante"},
      {name = "Issi", price = 26000, model = "issi2"},
      {name = "Panto", price = 5000, model = "panto"},
      {name = "Prairie", price = 32000, model = "prairie"},
      {name = "Rhapsody", price = 29000, model = "Rhapsody"},
   },
   ["Coupes"] = {
      {name = "Cognoscenti Cabrio", price = 50000, model = "CogCabrio"},
      {name = "Exemplar", price = 60000, model = "Exemplar"},
      {name = "F620", price = 75000, model = "F620"},
      {name = "Felon", price = 72000, model = "Felon"},
      {name = "Felon GT", price = 75000, model = "Felon2"},
      {name = "Jackal", price = 68000, model = "Jackal"},
      {name = "Oracle XS", price = 65000, model = "Oracle"},
      {name = "Oracle", price = 68000, model = "Oracle2"},
      {name = "Sentinel XS", price = 70000, model = "Sentinel"},
      {name = "Sentinel", price = 72000, model = "Sentinel2"},
      {name = "Windsor", price = 80000, model = "Windsor"},
      {name = "Windsor Drop", price = 90000, model = "Windsor2"},
      {name = "Zion", price = 70000, model = "Zion"},
      {name = "Zion Cabrio", price = 75000, model = "Zion2"},
   },
   ["Motorcycles"] = {
      {name = "Akuma", price = 60000, model = "Akuma"},
      {name = "Avarus", price = 55000, model = "Avarus"},
      {name = "Bagger", price = 65000, model = "Bagger"},
      {name = "Bati 801RR", price = 90000, model = "Bati2"},
      {name = "Bati 801", price = 80000, model = "Bati"},
      {name = "BF400", price = 55000, model = "BF400"},
      {name = "Street Blazer", price = 70000, model = "Blazer4"},
      {name = "Carbon RS", price = 65000, model = "CarbonRS"},
      {name = "Chimera", price = 65000, model = "Chimera"},
      {name = "Cliffhanger", price = 50000, model = "Cliffhanger"},
      {name = "Daemon", price = 60000, model = "Daemon2"},
      {name = "Lost Daemon", price = 65000, model = "Daemon"},
      {name = "Defiler", price = 55000, model = "Defiler"},
      {name = "Double-T", price = 85000, model = "Double"},
      {name = "Enduro", price = 45000, model = "Enduro"},
      {name = "Esskey", price = 45000, model = "Esskey"},
      {name = "Faggio Sport", price = 14000, model = "Faggio"},
      {name = "Faggio", price = 5000, model = "Faggio2"},
      {name = "Faggio Mod", price = 11000, model = "Faggio3"},
      {name = "FCR 1000 Custom", price = 45000, model = "Fcr2"},
      {name = "FCR 1000", price = 40000, model = "Fcr"},
   },
   ["Motorcycles Continued"] = {
      {name = "Gargoyle", price = 50000, model = "Gargoyle"},
      {name = "Hakuchou Drag", price = 95000, model = "Hakuchou2"},
      {name = "Hakuchou", price = 80000, model = "Hakuchou"},
      {name = "Hexer", price = 50000, model = "Hexer"},
      {name = "Innovation", price = 45000, model = "Innovation"},
      {name = "Lectro", price = 55000, model = "Lectro"},
      {name = "Manchez", price = 45000, model = "Manchez"},
      {name = "Nemesis", price = 45000, model = "Nemesis"},
      {name = "Nightblade", price = 65000, model = "Nightblade"},
      {name = "PCJ 600", price = 50000, model = "PCJ"},
      {name = "Rat Bike", price = 45000, model = "Ratbike"},
      {name = "Ruffian", price = 50000, model = "Ruffian"},
      {name = "Sanchez", price = 20000, model = "Sanchez2"},
      {name = "Sanchez (Livery)", price = 25000, model = "Sanchez"},
      {name = "Sanctus", price = 80000, model = "Sanctus"},
      {name = "Sovereign", price = 60000, model = "Sovereign"},
      {name = "Thrust", price = 50000, model = "Thrust"},
      {name = "Vader", price = 55000, model = "Vader"},
      {name = "Vindicator", price = 50000, model = "Vindicator"},
      {name = "Vortex", price = 45000, model = "Vortex"},
      {name = "Wolfsbane", price = 50000, model = "Wolfsbane"},
      {name = "Zombie Bobber", price = 60000, model = "Zombiea"},
   },
   ["Muscle"] = {
      {name = "Blade", price = 60000, model = "Blade"},
      {name = "Buccaneer", price = 40000, model = "Buccaneer"},
      {name = "Buccaneer Custom", price = 70000, model = "Buccaneer2"},
      {name = "Chino", price = 40000, model = "Chino"},
      {name = "Chino Custom", price = 45000, model = "Chino2"},
      {name = "Dominator", price = 90000, model = "Dominator"},
      {name = "Dukes", price = 50000, model = "Dukes"},
      {name = "Faction", price = 50000, model = "Faction"},
      {name = "Faction Custom Donk", price = 110000, model = "Faction3"},
      {name = "Gauntlet", price = 95000, model = "Gauntlet"},
      {name = "Hotknife", price = 80000, model = "Hotknife"},
      {name = "Moonbeam Custom", price = 60000, model = "Moonbeam2"},
      {name = "Nightshade", price = 75000, model = "Nightshade"},
      {name = "Phoenix", price = 55000, model = "Phoenix"},
      {name = "Ruiner", price = 50000, model = "Ruiner"},
      {name = "Sabre Turbo", price = 75000, model = "SabreGT"},
      {name = "Slamvan Custom", price = 80000, model = "SlamVan3"},
      {name = "Stalion", price = 55000, model = "Stalion"},
      {name = "Tampa", price = 60000, model = "Tampa"},
      {name = "Vigero", price = 50000, model = "Vigero"},
      {name = "Virgo", price = 50000, model = "Virgo"},
      {name = "Virgo Classic Custom", price = 75000, model = "Virgo2"},
      {name = "Voodoo Custom", price = 70000, model = "Voodoo"},
   },
   ["Off-Road"] = {
      {name = "Injection", price = 15000, model = "BfInjection"},
      {name = "Bifta", price = 20000, model = "Bifta"},
      {name = "Blazer", price = 12500, model = "Blazer"},
      {name = "Bodhi", price = 11000, model = "Bodhi2"},
      {name = "Brawler", price = 90000, model = "Brawler"},
      {name = "Dune Buggy", price = 15000, model = "Dune"},
      {name = "Mesa", price = 60000, model = "Mesa"},
      {name = "Army Mesa", price = 80000, model = "Mesa3"},
      {name = "Rancher XL", price = 14500, model = "RancherXL"},
      {name = "Rebel", price = 25000, model = "Rebel2"},
      {name = "Sandking XL", price = 100000, model = "Sandking"},
      {name = "Trophy Truck", price = 110000, model = "TrophyTruck"},
      {name = "Desert Raid", price = 150000, model = "TrophyTruck2"},
   },
   ["SUVs"] = {
      {name = "BeeJay XL", price = 55000, model = "BJXL"},
      {name = "Baller", price = 70000, model = "Baller2"},
      {name = "Cavalcade", price = 40000, model = "Cavalcade"},
      {name = "Cavalcade Sport", price = 45000, model = "Cavalcade2"},
      {name = "Contender", price = 120000, model = "Contender"},
      {name = "Dubsta", price = 55000, model = "Dubsta"},
      {name = "Dubsta Sport", price = 70000, model = "Dubsta2"},
      {name = "Dubsta 6x6", price = 90000, model = "Dubsta3"},
      {name = "FQ 2", price = 50000, model = "FQ2"},
      {name = "Granger", price = 55000, model = "Granger"},
      {name = "Gresley", price = 45000, model = "Gresley"},
      {name = "Habanero", price = 35000, model = "Habanero"},
      {name = "Huntley S", price = 55000, model = "Huntley"},
      {name = "Landstalker", price = 47500, model = "Landstalker"},
      {name = "Patriot", price = 85000, model = "Patriot"},
      {name = "Radius", price = 40000, model = "Radi"},
      {name = "Rocoto", price = 45000, model = "Rocoto"},
      {name = "Seminole", price = 38500, model = "Seminole"},
      {name = "Serrano", price = 38000, model = "Serrano"},
      {name = "XLS", price = 40000, model = "XLS"},
   },
   ["Sedans"] = {
      {name = "Asea", price = 45000, model = "Asea"},
      {name = "Asterope", price = 60000, model = "Asterope"},
      {name = "Cognescenti 55", price = 65000, model = "Cog55"},
      {name = "Emperor", price = 30000, model = "Emperor"},
      {name = "Fugitive", price = 70000, model = "Fugitive"},
      {name = "Glendale", price = 45000, model = "Glendale"},
      {name = "Ingot", price = 35000, model = "Ingot"},
      {name = "Intruder", price = 50000, model = "Intruder"},
      {name = "Premier", price = 35000, model = "Premier"},
      {name = "Primo", price = 35000, model = "Primo"},
      {name = "Regina", price = 30000, model = "Regina"},
      {name = "Stanier", price = 35000, model = "Stanier"},
      {name = "Stratum", price = 35000, model = "Stratum"},
      {name = "Stretch", price = 80000, model = "Stretch"},
      {name = "Surge", price = 40000, model = "Surge"},
      {name = "Tailgater", price = 50000, model = "Tailgater"},
      {name = "Warrener", price = 40000, model = "Warrener"},
      {name = "Washington", price = 35000, model = "Washington"},
   },
   ["Sports"] = {
      {name = "Alpha", price = 95000, model = "Alpha"},
      {name = "Banshee", price = 130000, model = "Banshee"},
      {name = "Banshee 900R", price = 180000, model = "Banshee2"},
      {name = "Bestia GTS", price = 95000, model = "BestiaGTS"},
      {name = "Buffalo S", price = 85000, model = "Buffalo2"},
      {name = "Sprunk Buffalo", price = 100000, model = "Buffalo3"},
      {name = "Carbonizzare", price = 120000, model = "Carbonizzare"},
      {name = "Comet Retro Custom", price = 95000, model = "Comet3"},
      {name = "Coquette", price = 105000, model = "Coquette"},
      {name = "Elegy Retro Custom", price = 85000, model = "Elegy"},
      {name = "Elegy RH8", price = 105000, model = "Elegy2"},
      {name = "Feltzer", price = 105000, model = "Feltzer2"},
      {name = "Stirling GT", price = 110000, model = "Feltzer3"},
      {name = "Furore GT", price = 125000, model = "Furoregt"},
      {name = "Fusilade", price = 85000, model = "Fusilade"},
      {name = "Futo", price = 60000, model = "Futo"},
      {name = "Infernus Classic", price = 150000, model = "Infernus2"},
      {name = "Jester", price = 200000, model = "Jester"},
      {name = "Jester (Racecar)", price = 250000, model = "Jester2"},
   },
   ["Sports Continued"] = {
      {name = "Khamelion", price = 135000, model = "Khamelion"},
      {name = "Kuruma", price = 105000, model = "Kuruma"},
      {name = "Lynx", price = 135000, model = "Lynx"},
      {name = "Massacro", price = 125000, model = "Massacro"},
      {name = "Massacro (Racecar)", price = 145000, model = "Massacro2"},
      {name = "9F", price = 110000, model = "Ninef"},
      {name = "9F Cabrio", price = 120000, model = "Ninef2"},
      {name = "Omnis", price = 135000, model = "Omnis"},
      {name = "Penumbra", price = 105000, model = "Penumbra"},
      {name = "Rapid GT", price = 135000, model = "RapidGT"},
      {name = "Raptor", price = 100000, model = "Raptor"},
      {name = "Ruston", price = 170000, model = "Ruston"},
      {name = "Schwarzer", price = 95000, model = "Schwarzer"},
      {name = "Seven-70", price = 140000, model = "Seven70"},
      {name = "Specter", price = 140000, model = "Specter"},
      {name = "Specter Custom", price = 145000, model = "Specter2"},
      {name = "Surano", price = 130000, model = "Surano"},
      {name = "Drift Tampa", price = 115000, model = "Tampa2"},
      {name = "Tropos Rallye", price = 115000, model = "Tropos"},
      {name = "Verlierer", price = 120000, model = "Verlierer2"},
   },
   ["Sports Classic"] = {
      {name = "Roosevelt", price = 160000, model = "BType"},
      {name = "Casco", price = 120000, model = "Casco"},
      {name = "Cheetah Classic", price = 160000, model = "Cheetah2"},
      {name = "Coquette Classic", price = 140000, model = "Coquette2"},
      {name = "Coquette BlackFin", price = 150000, model = "Coquette3"},
      {name = "Mamba", price = 120000, model = "Mamba"},
      {name = "Manana", price = 70000, model = "Manana"},
      {name = "Monroe", price = 105000, model = "Monroe"},
      {name = "Peyote", price = 75000, model = "Peyote"},
      {name = "Pigalle", price = 80000, model = "Pigalle"},
      {name = "Stinger", price = 105000, model = "Stinger"},
      {name = "Stinger GT", price = 125000, model = "StingerGT"},
      {name = "Torero", price = 110000, model = "Torero"},
      {name = "Tornado", price = 85000, model = "Tornado"},
      {name = "Z-Type", price = 110000, model = "ZType"},
   },
   ["Super"] = {
      {name = "Adder", price = 700000, model = "Adder"},
      {name = "Bullet", price = 420000, model = "Bullet"},
      {name = "Cheetah", price = 450000, model = "Cheetah"},
      {name = "Entity XF", price = 675000, model = "EntityXF"},
      {name = "FMJ", price = 700000, model = "FMJ"},
      {name = "GP1", price = 525000, model = "GP1"},
      {name = "Infernus", price = 450000, model = "Infernus"},
      {name = "Nero", price = 725000, model = "Nero"},
      {name = "Nero Custom", price = 850000, model = "Nero2"},
      {name = "Osiris", price = 575000, model = "Osiris"},
      {name = "Penetrator", price = 500000, model = "Penetrator"},
      {name = "Pfister 811", price = 575000, model = "Pfister811"},
      {name = "X80 Proto", price = 675000, model = "Prototipo"},
   },
   ["Super Continued"] = {
      {name = "Reaper", price = 450000, model = "Reaper"},
      {name = "ETR1", price = 500000, model = "Sheava"},
      {name = "T20", price = 550000, model = "T20"},
      {name = "Tempesta", price = 500000, model = "Tempesta"},
      {name = "Turismo Classic", price = 400000, model = "Turismo2"},
      {name = "Turismo R", price = 575000, model = "Turismor"},
      {name = "Tyrus", price = 550000, model = "Tyrus"},
      {name = "Vacca", price = 400000, model = "Vacca"},
      {name = "Vagner", price = 600000, model = "Vagner"},
      {name = "Voltic", price = 475000, model = "Voltic"},
      {name = "Zentorno", price = 675000, model = "Zentorno"},
      {name = "Itali GTB Custom", price = 500000, model = "Italigtb2"},
      {name = "XA-21", price = 650000, model = "XA21"},
   },
   ["Vans"] = {
      {name = "Bison", price = 30000, model = "Bison"},
      {name = "Bobcat XL", price = 35000, model = "BobcatXL"},
      {name = "Burrito", price = 26000, model = "Burrito3"},
      {name = "Camper", price = 28000, model = "Camper"},
      {name = "Gang Burrito", price = 30000, model = "GBurrito"},
      {name = "Gang Burrito", price = 35000, model = "GBurrito2"},
      {name = "Journey", price = 30000, model = "Journey"},
      {name = "Minivan", price = 33000, model = "Minivan"},
      {name = "Minivan Custom", price = 33000, model = "Minivan2"},
      {name = "Paradise", price = 28000, model = "Paradise"},
      {name = "Rumpo", price = 28000, model = "Rumpo"},
      {name = "Rumpo Custom", price = 80000, model = "Rumpo3"},
      {name = "Speedo", price = 38000, model = "Speedo"},
      {name = "Clown Van", price = 44000, model = "Speedo2"},
      {name = "Surfer", price = 40000, model = "Surfer"},
      {name = "Youga", price = 32000, model = "Youga"},
      {name = "Youga Classic", price = 30000, model = "Youga2"},
   },
}

