RegisterServerEvent('core:characterloaded')
AddEventHandler('core:characterloaded', function()
 TriggerEvent("core:getPlayerFromId", source, function(user)
  TriggerClientEvent('repuation:set', source, user.getReputation())
 end)
end)

TriggerEvent('core:addCommand', 'rep', function(source, args, user)
 TriggerEvent("core:getPlayerFromId", source, function(user)
  TriggerClientEvent('chatMessage', source, '^4Reputation: '..user.getReputation())
 end)
end)

RegisterServerEvent('addReputation')
AddEventHandler('addReputation', function(v)
 TriggerEvent("core:getPlayerFromId", source, function(user)
   user.addReputation(v)
 end)
end)

RegisterServerEvent('removeReputation')
AddEventHandler('removeReputation', function(v)
 TriggerEvent("core:getPlayerFromId", source, function(user)
   user.removeReputation(v)
 end)
end)

RegisterServerEvent('setReputation')
AddEventHandler('setReputation', function(v)
 TriggerEvent("core:getPlayerFromId", source, function(user)
  user.setReputation(v)
 end)
end)