Citizen.CreateThread(function()
	AddTextEntry('lp770cop', 'Police Centenario')
	AddTextEntry('police2', 'Police Charger')
	AddTextEntry('police5', 'Police Explorer')
	AddTextEntry('police7', 'Police Crown Victoria')
	AddTextEntry('bearcat', 'CRT Bearcat')
	AddTextEntry('f750', 'EMS Ambulance')
	AddTextEntry('fd1', 'EMS Explorer')
	AddTextEntry('fd2', 'EMS Tahoe')
	AddTextEntry('fd3', 'EMS Crown Victoria')
	AddTextEntry('fd4', 'EMS Taurus')
	AddTextEntry('polmav', 'EMS Maverick')
	AddTextEntry('rmodx6', 'BMW X5')
	AddTextEntry('gt17', 'Ford GT')
	AddTextEntry('GT86', 'Toyota GT-86')
	AddTextEntry('720s', 'McClaren 720s')
	AddTextEntry('lanex400', 'Mitsubishi Lancer')
	AddTextEntry('a80', 'Toyota Supra')
	AddTextEntry('2013rs7', 'Audi RS7')
	AddTextEntry('na1', 'Honda NSX R')
	AddTextEntry('contss18', 'Bentley Continental GT')
	AddTextEntry('hcbr17', 'Honda CBR 1000RR')
	AddTextEntry('FK8', 'Honda TypeR')
	AddTextEntry('urus', 'Lamborghini Urus')
	AddTextEntry('slingshot', 'Polaris Slingshot')
	AddTextEntry('teslax', 'Tesla Model X')
	AddTextEntry('f82', 'BMW M4 Liberty Walk')
	AddTextEntry('mgt', 'Ford Mustang')
	AddTextEntry('fd', 'Mazda RX7')
	AddTextEntry('rrphantom', 'Rolls Royce Phantom')
	AddTextEntry('subisti08', 'Subaru WRX STi')
	AddTextEntry('golfp', 'Volkswagen Golf R')
	AddTextEntry('m3e30', 'BMW M3 E30')
	AddTextEntry('p911r', 'Porsche RUF RGT-8 GT3')
	AddTextEntry('e400', 'Mercedes E400')
	AddTextEntry('mxpan', 'Mazda MX-5')
end)