RegisterServerEvent('core:characterloaded')
AddEventHandler('core:characterloaded', function()
 local source = tonumber(source)
 TriggerEvent("core:getPlayerFromId", source, function(user)
  local result = exports['GHMattiMySQL']:QueryScalar("SELECT jail FROM `characters` WHERE id=@char_id",{['@char_id'] = user.getCharacterID()})
  if result > 0 then
   local jailtime = result
   TriggerClientEvent("prison:jail", source, jailtime)
  end
 end)
end)

RegisterServerEvent('prison:checkTime')
AddEventHandler('prison:checkTime', function()
  local source = tonumber(source)
  TriggerEvent("core:getPlayerFromId", source, function(user)
   local result = exports['GHMattiMySQL']:QueryScalar("SELECT jail FROM `characters` WHERE id=@char_id",{['@char_id'] = user.getCharacterID()})
   if result > 0 then
    local jailtime = result
    TriggerClientEvent("prison:jail", source, jailtime)
   end
  end)
end)

RegisterServerEvent('prison:jailplayer')
AddEventHandler('prison:jailplayer', function(target, time)
 local target = tonumber(target)
 TriggerEvent("core:getPlayerFromId", target, function(user)
   local character = user.getIdentity()
   TriggerClientEvent('police:uncuff', target) 
   --TriggerClientEvent("pNotify:SendNotification", -1, {text = "Government: "..character.firstname.." "..character.lastname.." Has Been Jailed For ".. time .." Months", layout = 'bottomRight'})
   TriggerClientEvent('NRP-notify:client:SendAlert', source, { type = 'inform', text = "Government: "..character.firstname.." "..character.lastname.." has been jailed for ".. time .." months."})
   TriggerClientEvent("prison:jail", target, time)
   TriggerEvent("core:log", tostring("[JAIL] "..GetPlayerName(source).."]("..source..") has jailed "..character.fullname.."("..target..") for "..time.." months."), "jail")
   exports['GHMattiMySQL']:QueryAsync("UPDATE `characters` SET jail=@jailtime WHERE id=@id",{['@jailtime'] = time, ['@id'] = user.getCharacterID()})
   --user.removeReputation(100)
 end)
end)

RegisterServerEvent('prison:fineplayer')
AddEventHandler('prison:fineplayer', function(target, finee)
 local source = tonumber(source)
 local target = tonumber(target)
 local fine = tonumber(finee)
 TriggerEvent("core:getPlayerFromId", target, function(user)
  user.removeBank(fine)
  local character = user.getIdentity()
  TriggerEvent("core:log", tostring("[FINE] "..GetPlayerName(source).."]("..source..") has fined "..character.fullname.."("..target..") for $"..fine.."."), "fine")
  TriggerClientEvent('NRP-notify:client:SendAlert', target, { type = 'inform', text = "You Have Been Fined: $"..fine})
  TriggerClientEvent('NRP-notify:client:SendAlert', source, { type = 'inform', text = "Fine Sent"})
 end)
end)

RegisterServerEvent('prison:jailtime')
AddEventHandler('prison:jailtime', function(time)
 TriggerEvent("core:getPlayerFromId", source, function(user)
  exports['GHMattiMySQL']:QueryAsync("UPDATE `characters` SET jail=@jailtime WHERE id=@id",{['@jailtime'] = time, ['@id'] = user.getCharacterID()})
 end)
end)

RegisterServerEvent('prison:jail')
AddEventHandler('prison:jail', function(time)
 local target = tonumber(source)
 TriggerEvent("core:getPlayerFromId", target, function(user)
   local character = user.getIdentity()
   TriggerClientEvent('police:uncuff', target)
   --TriggerClientEvent("pNotify:SendNotification", -1, {text = "<font color='lightblue'>Government: <font color='white'>"..character.firstname.." "..character.lastname.." <font color='white'>Has Been Jailed For ".. time .." Months", layout = 'bottomRight'})
   TriggerClientEvent('NRP-notify:client:SendAlert', -1, { type = 'inform', text = "Government: "..character.firstname.." "..character.lastname.."Has Been Jailed For ".. time .." Months"})
   TriggerClientEvent("prison:jail", target, time)
   exports['GHMattiMySQL']:QueryAsync("UPDATE `characters` SET jail=@jailtime WHERE id=@id",{['@jailtime'] = time, ['@id'] = user.getCharacterID()})
 end)
end)

RegisterServerEvent('prison:fine')
AddEventHandler('prison:fine', function(finee)
 local target = tonumber(source)
 local fine = tonumber(finee)
 TriggerEvent("core:getPlayerFromId", target, function(user)
  user.removeBank(fine)
  local character = user.getIdentity()
  TriggerClientEvent('NRP-notify:client:SendAlert', target, { type = 'inform', text = "You Have Been Fined: $"..fine})
 end)
end)

RegisterServerEvent('prison:history')
AddEventHandler('prison:history', function(id, charges, fine, time)
  local targetSource = tonumber(id)
  TriggerEvent("core:getPlayerFromId", source, function(user)
    TriggerEvent("core:getPlayerFromId", targetSource, function(target)
      exports['GHMattiMySQL']:QueryAsync('INSERT INTO `mdt_history` (char_id, name, fine, time, charges, officer) VALUES (@id, @name, @fine, @time, @charges, @officer)',{['@id'] = target.getCharacterID(), ['@name'] = target.getIdentity().fullname, ['@fine'] = fine, ['@time'] = time, ['@charges'] = charges, ['@officer'] = user.getIdentity().fullname})
    end)
  end)
end)
